apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: qa
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: main
        cluster: qa
        url: https://kubernetes.default.svc
      - overlay: stage
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: main
        cluster: stage
        url: https://kubernetes.default.svc
      - overlay: prod
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: main
        cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}'