apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: qa
        gitRepo: https://github.com/evercast-chris/argocd-example-apps.git
        appPath: overlays
        appBranch: master
        cluster: qa
        url: https://kubernetes.default.svc
      - overlay: stage
        gitRepo: https://github.com/evercast-chris/argocd-example-apps.git
        appPath: overlays
        appBranch: master
        cluster: stage
        url: https://kubernetes.default.svc
      - overlay: prod
        gitRepo: https://github.com/evercast-chris/argocd-example-apps.git
        appPath: overlays
        appBranch: master
        cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'test-{{cluster}}'