apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
     # v0.2.0+ form - does not require cluster/URL keys (but are still supported)
      - overlay: qa
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: master
        cluster: qa
        url: https://kubernetes.default.svc
      - overlay: stage
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: master
        cluster: stage
        url: https://kubernetes.default.svc
      - overlay: prod
        gitRepo: git@github.com:jcquiles/ArgoCD.git
        appPath: overlays
        appBranch: master
        cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'demo-{{cluster}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}/{{overlay}}'
      destination:
        server: '{{url}}'