apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../argocd-base/app-of-apps/ 

namespace: argocd

patchesStrategicMerge:
- rootapp.yaml

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: parent-app
    path: RootAppNamePatch.yaml