apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jcquiles/ArgoCD.git
    targetRevision: main
    path: argocd-overlays/applicationsets
